### ISSUE TITLE
Menu Bundle depends on CoreBundle

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/menu-bundle#253]
When activating the MenuBundle:

```
The service "cmf_menu.publish_workflow.create_menu_item_from_node_listener" has a dependency on a non-existent service "cmf_core.publish_workflow.checker"
```

This can be avoided by disabling the publish workflow checker (which is enabled by default).

**Comment by dantleech** [comment]
I think we should move the "publsh workflow" to a separate component / bundle for 2.0, and also give it some attention.

**Comment by dbu** [comment]
the idea was that core bundle provides common things like the publish workflow. if this is the only service we depend on, we could make publish workflow optional and skip it if not defined.

the problem with making publish workflow separate is that we would then either have to depend on it from menu and content bundle, or we would increase the complexity by having a menu without publish workflow and then one provided by the publish workflow component, and having to select between those and so on.

**Comment by dantleech** [comment]
In general I think the publish workflow, or however that concept might be expanded, is one thing that could be generally useful and it warrants its own dedicated component.

Not sure how MenuBundle would be more complicated than now if we depend on a PWF component / bundle rather than the `CoreBundle`? (afaik the MenuBundle requires the CoreBundle only for PWF).

Currently the MenuBundle does not explicitly depend on `CoreBundle`, and you can disable the PWF integration, so I think in the short term it would suffice to simply default to `enabled: auto`.

**Comment by dbu** [comment]
see #258
