### ISSUE TITLE
Incorrect exception when requested menu does not exist.

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/menu-bundle#255]
The [exception](https://github.com/symfony-cmf/menu-bundle/blob/master/Provider/PhpcrMenuProvider.php#L249) is thrown as follows:

```
The menu root "/cms/contents" doe not exist.
```

When the menu root _does_ exist but the requested menu doesn't.

**Comment by ElectricMaxxx** [comment]
Is that relevant for 2.0 or gone through the admin extension?

**Comment by wouterj** [comment]
This is not related to sonata at all, so still relevant.
