### ISSUE TITLE
symfony 3.0 support

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/menu-bundle#279]
we should either re-enable building with symfony 3.0 or only allow 2.8 and 3.1. see 
https://github.com/symfony-cmf/menu-bundle/pull/278#discussion_r91844021

**Comment by wouterj** [comment]
I think we should not test against 3.0. But I have no problems keeping support or it in the `composer.json`. These are my reasons:

 * Symfony 3.0 has exactly the same API as 2.8 (if we ignore BC layers in 2.8), we test against 2.8
 * Symfony 3.0's codebase only receives security bug fixes. This means no behaviour whatsoever is changed, so if tests pass now (and they did pass) they will always pass.
 * Security fixes changing behaviour in 3.0 will have exactly the same behaviour change in 3.1 and 3.2, which we test against.
 * We have no code in our codebase specifically targetting 3.0 only.
